[package]
name = "log-execution-time"
version = "0.1.0"
edition = "2021"
authors = ["Satish Babariya <satish.babariya@gmail.com>"]
license = "MIT"

[dependencies]
quote = "1.0.38"
syn = { version = "2.0", features = ["full"] }

[lib]
proc-macro = true
